# Generated by Django 4.2.1 on 2023-06-02 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('H', 'HTML5'), ('C', 'CSS'), ('J', 'JavaScript'), ('P', 'Python')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='code',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
