# Generated by Django 4.2.1 on 2023-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_code_language_code_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='github',
            field=models.URLField(default='https://www.youtube.com/watch?v=b4jwe4TcqIw&ab_channel=BenManley'),
        ),
    ]
